In [93]:
# Question 1 : Get the positions where elements of a and b match.
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [94]:
# Solution 1 :
np.where(a == b) # a == b returns a boolean array and np.where() gives index where condition is true.

(array([1, 3, 5, 7]),)

In [95]:
# Question 2 : Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)

[ 2  6  1  9 10  3 27]


In [96]:
# Solution 2 :
a[(a >= 5) & (a <= 10)] # Bitwise AND of two condition

array([ 6,  9, 10])

In [97]:
# Question 3 : Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [98]:
# Solution 3 :
arr[:, [1,0,2]] # Fancy indexing

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [99]:
# Question 4 : Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [100]:
# Solution 4 :
arr[[i for i in range(arr.shape[0]-1, -1, -1)]] # Using range function to iterate in backdirection taking steps as -1.

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [101]:
# Question 5 : Find the 5th and 95th percentile of iris's sepallength Note - Find input code in the next cell
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(sepallength)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [102]:
# Solution 5
fifthPercentile = np.percentile(sepallength, 5)
nintyfifthPercentile = np.percentile(sepallength, 95)
print("5th percetile is : " + str(fifthPercentile))
print("95th percetile is : " + str(nintyfifthPercentile))

5th percetile is : 4.6
95th percetile is : 7.254999999999998


In [105]:
# Question 6 : Find the positions of NaN in the sepalLength numpy array
# This is the input of your question
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

sepalLength=iris_2d[:,0]
# This is the sepalLength
print(sepalLength)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 nan 4.7 4.8 5.4 5.2 5.5 4.9 5.
 nan 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  nan nan 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 nan
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 nan 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [106]:
# Solution 6
np.where(np.isnan(sepalLength)) # np.isnan() gives boolean array, true at position where nan is present. np.where() tells position where it is true.

(array([ 28,  36,  79,  80, 125, 135]),)

In [107]:
# Question 7 : Replace all the null values with 0 in the above used sepalLength array

In [108]:
# Solution 7 :
sepalLength[np.isnan(sepalLength)] = 0
print(sepalLength)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 0.  4.7 4.8 5.4 5.2 5.5 4.9 5.
 0.  4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  0.  0.  5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 0.
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 0.  6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [109]:
# Question 8 : Find the 2nd largest value for the given array.
# Input
arr=np.random.randint(23,78, size=9).reshape(3,3)
arr

array([[73, 66, 75],
       [26, 57, 54],
       [71, 62, 45]])

In [110]:
# Solution 8 :
arrcpy = np.ravel(arr) # np.ravel() converts array to 1 dimensional array
arrcpy.sort() # So that i can get 2nd last element using negative indexing
arrcpy[-2]

73

In [111]:
# Question 9 : From the array a, replace all values greater than 30 by 30 and less than 10 by 10.
# Input
arr=np.random.randint(1,78, size=9).reshape(3,3)
print(arr)

[[ 5  3 25]
 [12 25  7]
 [21 46 28]]


In [112]:
# Solution 9 :
arr[arr > 30] = 30
arr[arr < 10] = 10
arr

array([[10, 10, 25],
       [12, 25, 10],
       [21, 30, 28]])

In [113]:
# Question 10 : Drop all nan values from a 1D numpy array.
arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
print(arr)

[ 1.  2.  3. nan  5.  6.  7. nan]


In [114]:
# Solution 10 :
arr[~np.isnan(arr)] # Using bitwise NOT operation on boolean array as np.isnan() gives true where nan is present and we want to print remaining elements

array([1., 2., 3., 5., 6., 7.])