In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing
arr1[:,[3,1,2,0,4]] # Passing the list of the desired column number to have the required array.

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
arr1[[i for i in range(arr1.shape[0]-1, -1, -1)]] # To reverse ordering of rows, creating a list with back indexing i.e 3,2,1,0. using range function to take negative steps.

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
arr2[np.isnan(arr2)] = np.nanmean(arr2) # using np.nanmean() since normal mean() function will give nan. Using fancy indexing in arr2 where nan is present
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[82, 90, 14, 55],
       [46, 58, 10, 40],
       [88, 92, 12, 61],
       [84,  2, 76,  8],
       [27,  1, 44, 71]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
arr3[(arr3 > 23) | (arr3 % 3 == 0)] # Using bitwise OR operation in boolean values obtained on the basis of two given condition.

array([82, 90, 55, 46, 58, 40, 88, 92, 12, 61, 84, 76, 27, 44, 71])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [0]:
# In np.percentile() function we pass np array and the nth percentile number.
print("10th percentile : " + str(np.percentile(arr3, 10)))
print("25th percentile : " + str(np.percentile(arr3, 25)))
print("50th percentile : " + str(np.percentile(arr3, 50)))

10th percentile : 7.4
25th percentile : 13.5
50th percentile : 50.5
